### ISSUE TITLE
"Falha na inicialização"

### ISSUE THREAD

**Issue by guilhermesaraivaimpulso** [paulopinda/ruby-nbiobsp#1]
Bom dia Paulo,

Tentei utilizar seu sistema de integração da biometria com Ruby e me deparei com a seguinte mensagem; "Falha na inicialização"

Para a execução do sistema, eu instalei o Rice ( o Ruby eu ja possuia ), instalei as dependências assim como em seu tutorial, ( sudo apt-get install build-essential g++ autotools-dev libicu-dev libbz2-dev libboost-all-dev autoconf ) e executei o programa tests.rb da maneira que você falou, ( instalando os drives, criando o MakeFile, dando "make") mas acabo caindo no erro de "Falha na inicialização".

Não sei uma solução para este problema, tem alguma dica ? Acha que esqueci de instalar algo ?

Muito Obrigado pela atenção e pelo codigo !

**Comment by paulo-social** [comment]
Boa noite Guilherme,

Essa mensagem costuma aparecer quando o driver não está instalado ou não está licenciado. Tem um arquivo .lic no arquivo do driver, que precisa ser copiado para /lib, que é o arquivo de licenciamento. 

O dispositivo acende o led de leitura ao inicializar o driver, quando tudo está correto.

Att

**Comment by paulo-social** [comment]
Se não der certo, eu precisaria conectar ai pra ver.

**Comment by paulo-social** [comment]
Conforme conversamos por e-mail, faltava licenciar.
